const PASSWORD = "29052007";
const paths = { predictions: "../data/predictions/predictions_today.csv", tracking: "../tracking_results.csv" };
let predictions = []; let tracking = [];
const $ = (id) => document.getElementById(id);
function parseCsvLine(line){const result=[];let current="";let inQuotes=false;for(let i=0;i<line.length;i++){const char=line[i],next=line[i+1];if(char==='"'&&inQuotes&&next==='"'){current+='"';i++;}else if(char==='"'){inQuotes=!inQuotes;}else if(char===","&&!inQuotes){result.push(current);current="";}else{current+=char;}}result.push(current);return result;}
function csvParse(text){const lines=text.replace(/\r/g,"").split("\n").filter(Boolean);if(!lines.length)return[];const headers=parseCsvLine(lines[0]);return lines.slice(1).map(line=>{const values=parseCsvLine(line);const obj={};headers.forEach((h,i)=>obj[h]=values[i]??"");return obj;});}
function num(v){const n=Number(String(v??"").replace(",","."));return Number.isFinite(n)?n:0;}
function money(v){const n=num(v);return `${n>=0?"+":""}${n.toFixed(2)}€`;}
function pct(v){return `${(num(v)*100).toFixed(1)}%`;}
function escapeHtml(str){return String(str??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
async function fetchCsv(path){const res=await fetch(path+"?v="+Date.now());if(!res.ok)throw new Error(path);return csvParse(await res.text());}
async function loadData(){ $("lastUpdate").textContent="Chargement des données..."; try{predictions=await fetchCsv(paths.predictions);}catch(e){predictions=[];} try{tracking=await fetchCsv(paths.tracking);}catch(e){tracking=[];} render(); }
function render(){const valueBets=predictions.filter(r=>r.decision==="VALUE BET").sort((a,b)=>num(b.value)-num(a.value));const wins=tracking.filter(r=>r.result==="WIN").sort((a,b)=>num(b.profit)-num(a.profit));const losses=tracking.filter(r=>r.result==="LOSS").sort((a,b)=>num(a.profit)-num(b.profit));const pending=tracking.filter(r=>!["WIN","LOSS"].includes(r.result||"")).sort((a,b)=>String(a.date).localeCompare(String(b.date)));const finished=[...wins,...losses];const totalStake=finished.reduce((s,r)=>s+num(r.stake||r.suggested_stake),0);const profit=finished.reduce((s,r)=>s+num(r.profit),0);const won=wins.reduce((s,r)=>s+Math.max(num(r.profit),0),0);const lost=losses.reduce((s,r)=>s+num(r.profit),0);const roi=totalStake>0?profit/totalStake:0;const winrate=finished.length?wins.length/finished.length:0;$("kpiValueBets").textContent=valueBets.length;$("kpiProfit").textContent=money(profit);$("kpiRoi").textContent=`${(roi*100).toFixed(1)}%`;$("kpiWinrate").textContent=`${(winrate*100).toFixed(1)}%`;$("roiStake").textContent=`${totalStake.toFixed(2)}€`;$("roiWon").textContent=money(won);$("roiLost").textContent=money(lost);$("roiNet").textContent=money(profit);$("lastUpdate").textContent=`Dernière MAJ : ${predictions[0]?.last_update||"Données chargées"}`;$("valueBetsList").innerHTML=valueBets.slice(0,30).map(card).join("")||empty("Aucun value bet.");$("winsList").innerHTML=wins.slice(0,60).map(r=>card(r,"win")).join("")||empty("Aucun pari gagné.");$("lossesList").innerHTML=losses.slice(0,60).map(r=>card(r,"loss")).join("")||empty("Aucun pari perdu.");$("pendingList").innerHTML=pending.slice(0,80).map(card).join("")||empty("Aucun pari en attente.");drawProfitChart(finished.sort((a,b)=>String(a.date).localeCompare(String(b.date))));}
function empty(text){return `<div class="bet-card">${escapeHtml(text)}</div>`;}
function card(r,status=""){const cls=status||(r.decision==="VALUE BET"?"value":"");const profit=r.profit!==undefined&&r.profit!==""?money(r.profit):"";const result=r.result?`<span class="badge ${r.result==="WIN"?"green":r.result==="LOSS"?"red":"amber"}">${escapeHtml(r.result)}</span>`:"";return `<article class="bet-card ${cls}"><div class="bet-top"><span>${escapeHtml(r.sport||"")}</span><span>${escapeHtml(r.date||"")}</span></div><div class="teams">${escapeHtml(r.home_team||"")}<br>vs ${escapeHtml(r.away_team||"")}</div><div class="badges"><span class="badge">${escapeHtml(r.market||"")}</span>${result}${r.ia_badge?`<span class="badge green">${escapeHtml(r.ia_badge)}</span>`:""}</div><div class="grid2"><span>Proba IA<br><b>${pct(r.ai_probability)}</b></span><span>Cote<br><b>${escapeHtml(r.bookmaker_odds||"")}</b></span><span>Value<br><b>${pct(r.value)}</b></span><span>Stake<br><b>${escapeHtml(r.stake||r.suggested_stake||"0")}€</b></span>${profit?`<span>Profit<br><b>${profit}</b></span>`:""}${r.final_winner?`<span>Gagnant<br><b>${escapeHtml(r.final_winner)}</b></span>`:""}</div></article>`;}
function drawProfitChart(rows){const canvas=$("profitChart");const ctx=canvas.getContext("2d");const dpr=window.devicePixelRatio||1;const rect=canvas.getBoundingClientRect();canvas.width=rect.width*dpr;canvas.height=180*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,rect.width,180);if(!rows.length){ctx.fillStyle="#9ea8c4";ctx.fillText("Pas encore assez de résultats.",16,32);return;}let cum=0;const points=rows.map((r,i)=>{cum+=num(r.profit);return{x:i,y:cum};});const minY=Math.min(0,...points.map(p=>p.y));const maxY=Math.max(0,...points.map(p=>p.y));const pad=18,w=rect.width-pad*2,h=180-pad*2,range=maxY-minY||1;ctx.strokeStyle="rgba(255,255,255,.15)";ctx.beginPath();ctx.moveTo(pad,pad+(maxY/range)*h);ctx.lineTo(pad+w,pad+(maxY/range)*h);ctx.stroke();ctx.strokeStyle="#34d399";ctx.lineWidth=3;ctx.beginPath();points.forEach((p,idx)=>{const x=pad+(points.length===1?0:(p.x/(points.length-1))*w);const y=pad+((maxY-p.y)/range)*h;if(idx===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.stroke();ctx.fillStyle="#f7f8ff";ctx.font="12px system-ui";ctx.fillText(`Profit cumulé : ${money(cum)}`,pad,18);}
function setupTabs(){document.querySelectorAll(".tab").forEach(btn=>{btn.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(b=>b.classList.remove("active"));document.querySelectorAll(".tab-panel").forEach(p=>p.classList.remove("active"));btn.classList.add("active");document.getElementById("tab-"+btn.dataset.tab).classList.add("active");});});}
function login(){const pass=$("passwordInput").value;if(pass===PASSWORD){localStorage.setItem("ps_auth","1");$("login").classList.add("hidden");$("dashboard").classList.remove("hidden");loadData();}else{$("loginError").textContent="Mot de passe incorrect.";}}
$("loginBtn").addEventListener("click",login);$("passwordInput").addEventListener("keydown",e=>{if(e.key==="Enter")login();});$("refreshBtn").addEventListener("click",loadData);setupTabs();if(localStorage.getItem("ps_auth")==="1"){$("login").classList.add("hidden");$("dashboard").classList.remove("hidden");loadData();}if("serviceWorker" in navigator){navigator.serviceWorker.register("service-worker.js").catch(()=>{});}
